// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    var_0 = scripts\mp\gametypes\br_quest_util.gsc::registerquestcategory( "domination", 1 );

    if ( !var_0 )
        return;

    scripts\mp\gametypes\br_quest_util.gsc::registertabletinit( "domination", ::domtablet_init );
    scripts\mp\gametypes\br_quest_util.gsc::registerremovequestinstance( "domination", ::domquest_removequestinstance );
    scripts\mp\gametypes\br_quest_util.gsc::registerquestlocale( "dom_locale" );
    scripts\mp\gametypes\br_quest_util.gsc::registercreatequestlocale( "dom_locale", ::domlocale_createquestlocale );
    scripts\mp\gametypes\br_quest_util.gsc::registercheckiflocaleisavailable( "dom_locale", ::domlocale_checkiflocaleisavailable );
    scripts\mp\gametypes\br_quest_util.gsc::registerremovequestinstance( "dom_locale", ::domlocale_removelocaleinstance );
    scripts\mp\gametypes\br_quest_util.gsc::registerquestcircletick( "dom_locale", ::domlocale_circletick );
    scripts\mp\gametypes\br_quest_util.gsc::registeronentergulag( "dom_locale", ::domlocale_onentergulag );
    scripts\mp\gametypes\br_quest_util.gsc::registeronrespawn( "dom_locale", ::domlocale_onrespawn );
    scripts\mp\gametypes\br_quest_util.gsc::getquestdata( "dom_locale" ).nextid = 0;
    scripts\mp\gametypes\br_quest_util.gsc::questtimerinit( "domination", 1 );
    scripts\mp\gametypes\br_quest_util.gsc::registerontimerexpired( "domination", ::dom_ontimerexpired );
    setupdom();
    game["dialog"]["mission_dom_accept"] = "mission_mission_dom_accept_secure";
    game["dialog"]["mission_dom_success"] = "mission_mission_dom_success";
}

domquest_removequestinstance()
{
    scripts\mp\gametypes\br_quest_util.gsc::releaseteamonquest( self.team );
    scripts\mp\gametypes\br_quest_util.gsc::uiobjectivehidefromteam( self.team );

    if ( isdefined( self.tablet.instance_alert_func ) )
        [[ self.tablet.instance_alert_func ]]( self );

    self.subscribedlocale thread domflagupdateiconsframeend();
}

domlocale_removelocaleinstance()
{
    foreach ( var_1 in self.subscribedinstances )
        var_1 thread scripts\mp\gametypes\br_quest_util.gsc::removequestinstance();

    deletedomflaggameobject();
    self.domflag = undefined;
}

domtablet_init()
{
    var_0 = getserachparams( self );
    var_1 = scripts\mp\gametypes\br_quest_util.gsc::findquestplacement( "domination", var_0 );

    if ( !isdefined( var_1 ) )
        return 0;

    disablelootspawnpoint( var_1.index );
    self.reservedplacement = var_1;
    return 1;
}

domlocale_createquestlocale( var_0 )
{
    scripts\mp\gametypes\br_quest_util.gsc::getquestdata( "dom_locale" ).nextid++;
    var_1 = scripts\mp\gametypes\br_quest_util.gsc::createlocaleinstance( "dom_locale", "domination", "DomPoint:" + scripts\mp\gametypes\br_quest_util.gsc::getquestdata( "dom_locale" ).nextid );

    if ( !isdefined( var_0 ) )
    {
        var_1.curorigin = ( 0, 0, 0 );
        var_1.enabled = 0;
        return var_1;
    }

    var_2 = var_0.origin;

    if ( !( var_0.spawnflags & 7 ) )
    {

    }

    var_3 = scripts\mp\gametypes\br_quest_util.gsc::questpointgetradius( var_0 );
    var_4 = spawn( "trigger_radius", var_2, 0, int( var_3 ), int( level.br_domheight ) );
    level.setdomscriptablepartstatefunc = ::domflag_setdomscriptablepartstate;
    var_5 = scripts\mp\gametypes\obj_dom.gsc::setupobjective( var_4 );
    var_5.onuse = ::domflag_onuse;
    var_5.onbeginuse = ::domflag_onbeginuse;
    var_5.onuseupdate = ::domflag_onuseupdate;
    var_5.onenduse = ::domflag_onenduse;
    var_5.usecondition = ::domflag_usecondition;
    var_5.lockupdatingicons = 1;
    var_5.checkuseconditioninthink = 1;

    if ( istrue( self.tablet.on_wztrain ) && isdefined( var_0.traincar ) )
    {
        if ( istrue( level.wztrain_info.dom_nocol ) )
            var_5.flagmodel setmodel( "lm_domination_point_01_mover_nocol" );
        else
            var_5.flagmodel setmodel( "lm_domination_point_01_mover" );

        var_6 = var_0.traincar.dom_offset;
        var_7 = var_0.traincar.angles;

        if ( isdefined( var_0.traincar.dom_angles ) )
            var_7 = var_0.traincar.dom_angles;

        var_5.flagmodel linkto( var_0.traincar.linked_model, "tag_origin", var_6, var_7 );
        var_4 enablelinkto();
        var_4 linkto( var_5.flagmodel );

        if ( isdefined( var_5.visuals ) && isarray( var_5.visuals ) )
        {
            foreach ( var_9 in var_5.visuals )
                var_9 linkto( var_5.flagmodel );
        }

        var_5.scriptable linkto( var_0.traincar.linked_model );
        var_5.traincar = var_0.traincar;
        scripts\mp\objidpoolmanager::update_objective_onentity( var_5.objidnum, var_5.flagmodel );
    }
    else
    {
        var_5.flagmodel setmodel( "lm_domination_point_01" );
        scripts\mp\objidpoolmanager::update_objective_position( var_5.objidnum, var_5.curorigin + ( 0, 0, 60 ) );
    }

    level.flagcapturetime = getdvarfloat( "scr_br_dom_quest_capture_time", 30 );
    var_5 scripts\mp\gameobjects::setusetime( level.flagcapturetime );
    var_1.lastcircletick = -1;
    var_1.domflag = var_5;
    var_1.curorigin = var_5.curorigin;
    var_5.locale = var_1;
    scripts\mp\gametypes\br_quest_util.gsc::addquestinstance( "dom_locale", var_1 );
    return var_1;
}

domlocale_checkiflocaleisavailable( var_0 )
{
    var_1 = getdvarfloat( "scr_br_dom_quest_max_capture_percent", 0.2 );
    var_2 = getdvarfloat( "scr_br_dom_quest_max_teams", 4 );
    var_3 = 0;

    if ( isdefined( self.domflag.curprogress ) )
        var_3 = self.domflag.curprogress / self.domflag.usetime;

    if ( var_3 > var_1 )
        return 0;

    if ( self.subscribedinstances.size >= var_2 )
        return 0;

    return 1;
}

domlocale_circletick( var_0, var_1 )
{
    if ( !isdefined( self.domflag ) )
        return;

    var_2 = gettime();

    if ( self.lastcircletick == var_2 )
        return;

    self.lastcircletick = var_2;

    if ( isdefined( self.domflag ) && isdefined( self.domflag.traincar ) )
        self.curorigin = self.domflag.traincar.origin;

    var_3 = distance2d( self.curorigin, var_0 );

    if ( var_3 > var_1 )
    {
        foreach ( var_5 in self.subscribedinstances )
        {
            scripts\mp\gametypes\br_quest_util.gsc::displayteamsplash( var_5.team, "br_domination_quest_circle_failure" );
            level thread scripts\mp\gametypes\br_public.gsc::brleaderdialogteam( "mission_obj_circle_fail", var_5.team, 1 );
            var_5.result = "circle";

            if ( isdefined( var_5.tablet.instance_alert_func ) )
                [[ var_5.tablet.instance_alert_func ]]( var_5 );
        }

        scripts\mp\gametypes\br_quest_util.gsc::removequestinstance();
    }
}

domlocale_onentergulag( var_0 )
{
    domflag_hideiconfromplayer( var_0 );
}

domlocale_onrespawn( var_0 )
{
    if ( var_0.team == self.subscribedinstances[0].team )
        domflag_showicontoplayer( var_0 );
}

takequestitem( var_0 )
{
    var_1 = scripts\mp\gametypes\br_quest_util.gsc::createquestinstance( "domination", self.team, var_0.index, var_0 );
    var_1 scripts\mp\gametypes\br_quest_util.gsc::registerteamonquest( self.team, self );
    var_1 scripts\mp\gametypes\br_quest_util.gsc::registercontributingplayers( self );
    var_1.team = self.team;
    var_1.tablet = var_0;
    var_2 = getdvarint( "scr_br_DOM_questTime", 240 );
    var_1 scripts\mp\gametypes\br_quest_util.gsc::questtimerset( var_2, 4 );
    var_3 = getserachparams( var_0 );
    var_4 = var_1 scripts\mp\gametypes\br_quest_util.gsc::requestquestlocale( "dom_locale", var_3, 1 );

    if ( !var_4.enabled )
    {
        var_1.result = "no_locale";

        if ( isdefined( var_1.tablet.instance_alert_func ) )
            [[ var_1.tablet.instance_alert_func ]]( var_1 );

        var_1 scripts\mp\gametypes\br_quest_util.gsc::releaseteamonquest( self.team );
        return;
    }

    var_4 domflagupdateicons();
    scripts\mp\gametypes\br_quest_util.gsc::uiobjectiveshowtoteam( "domination", self.team );
    scripts\mp\gametypes\br_quest_util.gsc::addquestinstance( "domination", var_1 );
    scripts\mp\gametypes\br_quest_util.gsc::startteamcontractchallenge( "domination", self, self.team );
    var_5 = spawnstruct();
    var_5.excludedplayers = [];
    var_5.excludedplayers[0] = self;
    var_5.plundervar = scripts\mp\gametypes\br_quest_util.gsc::getquestplunderreward( "domination", scripts\mp\gametypes\br_quest_util.gsc::getquestrewardtier( self.team ) );
    scripts\mp\gametypes\br_quest_util.gsc::displayteamsplash( self.team, "br_domination_quest_start_team", var_5 );
    scripts\mp\gametypes\br_quest_util.gsc::displayplayersplash( self, "br_domination_quest_start_tablet_finder", var_5 );
    scripts\mp\gametypes\br_quest_util.gsc::giveteampoints( self.team, "br_mission_pickup_tablet" );
    scripts\mp\gametypes\br_quest_util.gsc::displaysquadmessagetoteam( var_1.team, self, 6, scripts\mp\gametypes\br_quest_util.gsc::getquestindex( "domination" ) );
    level thread scripts\mp\gametypes\br_public.gsc::brleaderdialogteam( "mission_dom_accept", var_1.team, 1 );
}

domflagupdateicons()
{
    objective_showtoplayersinmask( self.domflag.objidnum );
    objective_removeallfrommask( self.domflag.objidnum );

    foreach ( var_1 in self.subscribedinstances )
    {
        foreach ( var_3 in scripts\mp\utility\teams::getteamdata( var_1.team, "players" ) )
        {
            if ( !var_3 scripts\mp\gametypes\br_public.gsc::isplayeringulag() )
                objective_addclienttomask( self.domflag.objidnum, var_3 );
        }
    }
}

domflag_hideiconfromplayer( var_0 )
{
    objective_removeclientfrommask( self.domflag.objidnum, var_0 );
}

domflag_showicontoplayer( var_0 )
{
    objective_addclienttomask( self.domflag.objidnum, var_0 );
}

domflagupdateiconsframeend()
{
    self endon( "removed" );
    waittillframeend;
    domflagupdateicons();
}

deletedomflaggameobject()
{
    foreach ( var_1 in self.domflag.visuals )
        var_1 delete();

    if ( isdefined( self.domflag.flagmodel ) )
        self.domflag.flagmodel delete();

    if ( isdefined( self.domflag.scriptable ) )
        self.domflag.scriptable delete();

    if ( isdefined( self.domflag.trigger ) )
    {
        self.domflag.trigger delete();
        self.domflag.trigger = undefined;
    }

    self.domflag thread gameobjectreleaseid_delayed();
    self.domflag notify( "deleted" );
}

gameobjectreleaseid_delayed()
{
    wait 0.1;
    scripts\mp\gameobjects::releaseid();
}

setupdom()
{
    if ( isdefined( level.br_domheight ) )
        return;

    level.disableinitplayergameobjects = 0;
    level.br_domheight = 120;
    level.iconneutral = "waypoint_captureneutral_br";
    level.iconcapture = "waypoint_capture_br";
    level.icondefend = "waypoint_defend_br";
    level.icondefending = "waypoint_defending_br";
    level.iconcontested = "waypoint_contested_br";
    level.icontaking = "waypoint_taking_br";
    level.iconlosing = "waypoint_losing_br";
    level.iconovertime = "icon_waypoint_ot";
    _setdomflagiconinfo( "icon_waypoint_dom_br", "neutral", "MP_BR_INGAME/DOM_CAPTURE", 0 );
    _setdomflagiconinfo( "waypoint_taking_br", "friendly", "MP_INGAME_ONLY/OBJ_TAKING_CAPS", 1 );
    _setdomflagiconinfo( "waypoint_capture_br", "enemy", "MP_BR_INGAME/DOM_CAPTURE", 0 );
    _setdomflagiconinfo( "waypoint_defend_br", "friendly", "MP_INGAME_ONLY/OBJ_DEFEND_CAPS", 0 );
    _setdomflagiconinfo( "waypoint_defending_br", "friendly", "MP_INGAME_ONLY/OBJ_DEFENDING_CAPS", 0 );
    _setdomflagiconinfo( "waypoint_blocking_br", "friendly", "MP_INGAME_ONLY/OBJ_BLOCKING_CAPS", 0 );
    _setdomflagiconinfo( "waypoint_blocked_br", "friendly", "MP_INGAME_ONLY/OBJ_BLOCKED_CAPS", 0 );
    _setdomflagiconinfo( "waypoint_losing_br", "enemy", "MP_INGAME_ONLY/OBJ_LOSING_CAPS", 1 );
    _setdomflagiconinfo( "waypoint_captureneutral_br", "neutral", "MP_BR_INGAME/DOM_CAPTURE", 0 );
    _setdomflagiconinfo( "waypoint_contested_br", "contest", "MP_INGAME_ONLY/OBJ_CONTESTED_CAPS", 1 );
    _setdomflagiconinfo( "waypoint_dom_target_br", "neutral", "MP_INGAME_ONLY/OBJ_TARGET_CAPS", 0 );
    _setdomflagiconinfo( "icon_waypoint_target_br", "neutral", "MP_INGAME_ONLY/OBJ_TARGET_CAPS", 0 );
    _setdomflagiconinfo( "icon_waypoint_ot", "neutral", "MP_INGAME_ONLY/OBJ_OTFLAGLOC_CAPS", 0 );
}

_setdomflagiconinfo( var_0, var_1, var_2, var_3 )
{
    level.waypointcolors[var_0] = var_1;
    level.waypointbgtype[var_0] = 1;
    level.waypointstring[var_0] = var_2;
    level.waypointshader[var_0] = "ui_mp_br_mapmenu_icon_dom_objective";
    level.waypointpulses[var_0] = var_3;
}

domflag_onuseupdate( var_0, var_1, var_2, var_3 )
{
    if ( var_1 < 1.0 && !level.gameended )
        play_spotrep_capture_sfx( var_1, var_0 );

    if ( var_1 > 0.05 && var_2 && !istrue( self.didstatusnotify ) )
        self.didstatusnotify = 1;
}

domflag_onbeginuse( var_0 )
{
    if ( !isdefined( self.obj_icon_revealed ) || !self.obj_icon_revealed )
    {
        self.obj_icon_revealed = 1;

        if ( isdefined( self.traincar ) )
        {
            if ( isdefined( level.wztrain_info ) && istrue( level.wztrain_info.dom_use_flare ) )
            {
                var_1 = self.traincar.dom_offset + ( 200, 0, 0 );
                var_2 = self.traincar.origin + rotatevector( var_1, self.traincar.angles );
                level thread scripts\mp\gametypes\br_quest_util.gsc::utilflare_shootflare( var_2, "dom", 3 );
            }
        }
        else
            level thread scripts\mp\gametypes\br_quest_util.gsc::utilflare_shootflare( self.curorigin, "dom" );

        var_3 = scripts\mp\utility\player::getteamarray( var_0.team );
        var_4 = scripts\mp\utility\player::getplayersinradius( self.curorigin, 7800, undefined, var_3 );

        foreach ( var_6 in var_4 )
        {
            if ( isdefined( var_6 ) && isalive( var_6 ) )
                var_6 thread scripts\mp\hud_message::showsplash( "br_domination_quest_alert" );
        }

        var_8 = scripts\mp\utility\teams::getfriendlyplayers( var_0.team, 0 );

        foreach ( var_10 in var_8 )
            var_10 notify( "calloutmarkerping_warzoneKillQuestIcon" );
    }
}

domflag_onuse( var_0 )
{
    foreach ( var_2 in self.locale.subscribedinstances )
    {
        if ( var_2.team == var_0.team )
        {
            var_3 = spawnstruct();
            var_4 = scripts\mp\gametypes\br_quest_util.gsc::getquestrewardtier( var_0.team );
            var_5 = scripts\mp\gametypes\br_quest_util.gsc::getquestindex( "domination" );
            var_6 = scripts\mp\gametypes\br_quest_util.gsc::getquestrewardgroupindex( scripts\mp\gametypes\br_quest_util.gsc::getquestrewardbuildgroupref( "domination" ) );
            var_3.packedbits = scripts\mp\gametypes\br_quest_util.gsc::packsplashparambits( var_5, var_4, var_6 );
            scripts\mp\gametypes\br_quest_util.gsc::displayteamsplash( var_2.team, "br_domination_quest_complete", var_3 );
            scripts\mp\gametypes\br_quest_util.gsc::displaysquadmessagetoteam( var_2.team, var_0, 8, var_5 );
            level thread scripts\mp\gametypes\br_public.gsc::brleaderdialogteam( "mission_dom_success", var_2.team, 1, 1 );
            var_2.rewardorigin = self.flagmodel.origin;
            var_2.rewardangles = self.flagmodel.angles;
            var_2.result = "success";

            if ( isdefined( var_2.tablet.instance_alert_func ) )
                [[ var_2.tablet.instance_alert_func ]]( var_2 );

            if ( isdefined( self.assisttouchlist[var_2.team] ) )
            {
                var_7 = getarraykeys( self.assisttouchlist[var_2.team] );

                foreach ( var_9 in var_7 )
                {
                    var_10 = self.assisttouchlist[var_2.team][var_9].player;

                    if ( isdefined( var_10.owner ) )
                        var_10 = var_10.owner;

                    if ( !isplayer( var_10 ) )
                        continue;

                    var_10 scripts\cp_mp\challenges::reportt9userevent( "t9_ch_global_complete_recon_objective_for_operator_mission", 1 );
                    var_10 scripts\cp_mp\challenges::reportt9userevent( "t9_ch_global_complete_recon_objective_for_operator_mission_op2", 1 );
                    var_2 scripts\mp\gametypes\br_quest_util.gsc::registercontributingplayers( var_10 );
                }
            }

            continue;
        }

        scripts\mp\gametypes\br_quest_util.gsc::displayteamsplash( var_2.team, "br_domination_quest_failure" );
        level thread scripts\mp\gametypes\br_public.gsc::brleaderdialogteam( "mission_gen_fail", var_2.team, 1 );
        var_2.result = "fail";

        if ( isdefined( var_2.tablet.instance_alert_func ) )
            [[ var_2.tablet.instance_alert_func ]]( var_2 );
    }

    self.locale thread scripts\mp\gametypes\br_quest_util.gsc::removequestinstance();
}

domflag_onenduse( var_0, var_1, var_2 )
{
    scripts\mp\gametypes\obj_dom.gsc::dompoint_onuseend( var_0, var_1, var_2 );
}

play_spotrep_capture_sfx( var_0, var_1 )
{
    if ( !isdefined( self.lastsfxplayedtime ) )
        self.lastsfxplayedtime = gettime();

    if ( self.lastsfxplayedtime + 995 < gettime() )
    {
        self.lastsfxplayedtime = gettime();
        var_2 = "";
        var_0 = int( floor( var_0 * 10 ) );
        var_2 = "mp_dom_capturing_tick_0" + var_0;
        self.visuals[0] playsoundtoteam( var_2, var_1 );
    }
}

domflag_setdomscriptablepartstate( var_0, var_1, var_2 )
{
    switch ( var_1 )
    {
        case "contested":
        case "idle":
        case "off":
            return 0;
        default:
            var_1 = "using";

            if ( isdefined( var_2 ) )
                var_1 = var_1 + var_2;

            self.scriptable setscriptablepartstate( var_0, var_1 );

            if ( var_0 == "pulse" )
                self.scriptable setscriptablepartstate( "flag", var_1 );

            return 1;
    }
}

domflag_usecondition( var_0 )
{
    var_1 = var_0.team;

    foreach ( var_3 in self.locale.subscribedinstances )
    {
        if ( var_3.team == var_1 )
            return 1;
    }

    return 0;
}

dom_ontimerexpired()
{
    while ( self.subscribedlocale.domflag.numtouching[self.id] )
        waitframe();

    scripts\mp\gametypes\br_quest_util.gsc::displayteamsplash( self.id, "br_domination_quest_timer_expired" );
    level thread scripts\mp\gametypes\br_public.gsc::brleaderdialogteam( "mission_gen_fail", self.team, 1 );
}

getserachparams( var_0 )
{
    var_1 = spawnstruct();
    var_1.searchfunc = "questPointsArray";
    var_1.searchcircleorigin = ( var_0.origin[0], var_0.origin[1], 0 );
    var_1.searchradiusmax = 12000;
    var_1.searchradiusmin = 0;
    var_1.searchradiusidealmax = 8000;
    var_1.searchradiusidealmin = 6000;
    var_1.questtypes = 7;
    var_1.mintime = getdvarfloat( "scr_br_dom_quest_capture_time", 30 );
    var_1.searchforcecirclecenter = 1;
    var_1.reservedplacement = var_0.reservedplacement;

    if ( gametypeoverridedomsearchparams() )
    {
        if ( var_1.searchradiusmax < level.quest_domdistmax )
            var_1.searchradiusmax = level.quest_domdistmax;

        var_1.searchradiusidealmax = level.quest_domdistmax;
        var_1.searchradiusidealmin = level.quest_domdistmin;
    }

    if ( istrue( var_0.on_wztrain ) )
    {
        var_1.searchfunc = "questPointsArrayWZTrain";
        var_1.usefirstlocation = 1;
    }

    var_2 = getdvarint( "scr_br_questDomDistMin", -1 );
    var_3 = getdvarint( "scr_br_questDomDistMax", -1 );

    if ( var_2 >= 0 )
        var_1.searchradiusidealmin = var_2;

    if ( var_3 >= 0 )
        var_1.searchradiusidealmax = var_3;

    return var_1;
}

gametypeoverridedomsearchparams()
{
    var_0 = 0;
    var_1 = scripts\mp\utility\game::getsubgametype();

    switch ( var_1 )
    {
        case "mini":
        case "risk":
        case "dmz":
            var_0 = 1;
            break;
    }

    return var_0;
}
