// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

brlootcache_init()
{
    scripts\engine\scriptable::scriptable_addusedcallbackbypart( "body", ::lootcacheused );
    var_0 = getdvar( "scr_br_debug_loot_name", "" );
    var_1 = getdvar( "scr_br_debug_loot_probability", 0.0 );
    var_2 = strtok( var_0, " " );
    var_3 = strtok( var_1, " " );

    if ( var_3.size == 0 )
        var_3[var_3.size] = "1.0";

    level.brlootcache_debuglootitems = [];

    for ( var_4 = 0; var_4 < var_2.size; var_4++ )
    {
        var_5 = spawnstruct();
        var_5.name = var_2[var_4];
        var_6 = int( min( var_4, var_3.size - 1 ) );
        var_5.prob = float( var_3[var_6] );
        level.brlootcache_debuglootitems[level.brlootcache_debuglootitems.size] = var_5;
    }

    if ( istrue( level.halloweendvar ) )
    {
        setmatchdata( "halloweenTrickOrTreatRules", 1 );
        scripts\mp\holiday\halloween.gsc::init();
    }
}

canspawnitemname( var_0 )
{
    if ( !isdefined( var_0 ) )
        return 0;

    if ( scripts\mp\gametypes\br_public.gsc::isdmztutorial() )
    {
        if ( isdefined( level.forbiddencachespawns ) && isdefined( level.forbiddencachespawns[var_0] ) )
            return 0;
    }

    if ( var_0 == "brloot_respawn_token" && scripts\mp\gametypes\br_pickups.gsc::respawntokendisabled() )
        return 0;

    return 1;
}

lootspawnitem( var_0, var_1, var_2, var_3, var_4, var_5, var_6 )
{
    if ( istrue( var_4 ) )
    {
        var_7 = 35;

        if ( isdefined( var_6 ) )
        {
            var_8 = [ 115, 75, 95, 85, 105, 65 ];
            var_9 = ( var_1 + var_6 * 3 ) % var_8.size;
            var_10 = var_8[var_9];
            var_7 = var_7 + 20 * var_6;
        }
        else if ( var_1 % 2 > 0 )
            var_10 = 75;
        else
            var_10 = 115;

        var_10 = var_10 + randomfloatrange( -10, 10 );
        var_11 = var_7 + var_1 / 2 * 25 + randomfloatrange( -5, 5 );
        var_12 = scripts\mp\gametypes\br_pickups.gsc::getitemdroporiginandangles( var_1, var_2, var_3, undefined, var_10, var_11 );
    }
    else
        var_12 = scripts\mp\gametypes\br_pickups.gsc::getitemdroporiginandangles( var_1, var_2, var_3 );

    var_13 = level.br_pickups.counts[var_0];
    var_14 = undefined;
    var_15 = scripts\mp\gametypes\br_pickups.gsc::getfullweaponobjforscriptablepartname( var_0 );

    if ( isdefined( var_15 ) )
    {
        var_13 = scripts\mp\gametypes\br_weapons.gsc::br_getweaponstartingclipammo( var_15 );

        if ( scripts\mp\utility\weapon::isakimbo( var_15 ) )
            var_14 = var_13;
    }

    var_16 = scripts\mp\gametypes\br_pickups.gsc::spawnpickup( var_0, var_12, var_13, 1, undefined, undefined, var_14 );
    var_17 = level.br_pickups.br_itemrarity[var_0];

    if ( var_5 )
        playsoundatpos( var_12.origin, "br_legendary_loot_drop" );

    return var_16;
}

lootspawnitemlist( var_0, var_1, var_2 )
{
    var_3 = [];
    var_4 = 0;

    foreach ( var_6 in var_0 )
    {
        if ( canspawnitemname( var_6 ) )
        {
            var_7 = level.br_pickups.br_itemrarity[var_6];

            if ( isdefined( var_7 ) && var_7 == 4 && var_4 == 0 )
            {
                var_3[var_3.size] = lootspawnitem( var_6, self.itemsdropped, self.origin, self.angles, var_1, 1, var_2 );
                self.itemsdropped++;
                var_4 = 1;
            }
            else
            {
                var_3[var_3.size] = lootspawnitem( var_6, self.itemsdropped, self.origin, self.angles, var_1, 0, var_2 );
                self.itemsdropped++;
            }
        }
    }

    return var_3;
}

lootcachespawncontents( var_0, var_1 )
{
    return lootspawnitemlist( var_0, 1, var_1 );
}

closeagain( var_0 )
{
    level endon( "game_ended" );
    self endon( "death" );
    var_1 = getdvarint( "scr_reusable_cache_recharge_time", 90 );
    var_2 = 10;
    var_3 = 1;

    for ( var_4 = var_1 / var_2; var_3 < var_2; var_3++ )
    {
        wait( var_4 );
        self setscriptablepartstate( var_0, "vfx" + var_3 );
    }

    waitframe();
    var_5 = getdvarint( "scr_reusable_cache_loot_sets", 3 );
    self.currentset = ( self.currentset + 1 ) % var_5;
    self setscriptablepartstate( var_0, "closing" );
}

lootcacheused( var_0, var_1, var_2, var_3, var_4 )
{
    if ( istrue( var_3 scripts\mp\gametypes\br_gametypes.gsc::runbrgametypefunc( "playerSkipLootPickup", var_0 ) ) )
        return;

    if ( ( var_2 == "closed" || var_2 == "closed_nocol" ) && !isdefined( var_0.entity ) )
    {
        if ( var_2 == "closed" )
            var_0 setscriptablepartstate( var_1, "opening" );
        else if ( var_2 == "closed_nocol" )
            var_0 setscriptablepartstate( var_1, "opening_nocol" );

        var_0.itemsdropped = 0;
        var_5 = [];
        var_6 = 0;

        if ( var_0.type == "br_reusable_loot_cache" )
        {
            if ( !isdefined( var_0.currentset ) )
                var_0.currentset = 0;

            var_6 = var_0.currentset;
        }

        var_7 = getscriptablelootcachecontents( var_0, var_6 );

        if ( isdefined( var_7 ) )
            var_7 = lootcontentsadjustdebug( var_7, var_3 );

        if ( isdefined( var_7 ) && var_3 scripts\mp\utility\perk::_hasperk( "specialty_br_extra_killstreak_chance" ) )
            var_7 = lootcontentsadjustkillchain( var_7, var_3 );

        var_7 = lootcontentsadjustplunder( var_7, var_3 );

        if ( isdefined( var_7 ) )
        {
            if ( getdvar( "scr_br_gametype", "" ) == "dmz" || getdvar( "scr_br_gametype", "" ) == "risk" )
            {
                if ( scripts\mp\flags::gameflag( "placement_updates_allowed" ) )
                {
                    var_8 = game["teamPlacements"][var_3.team];

                    if ( !isdefined( level.dmz_numteamswithplayers ) )
                        scripts\mp\gametypes\br_gametype_dmz.gsc::calculatenumteamswithplayers();

                    var_9 = 100 - 100 * var_8 / level.dmz_numteamswithplayers;

                    if ( isdefined( level.bottompercentagetoadjusteconomy ) && var_9 < level.bottompercentagetoadjusteconomy )
                        var_7 = lootcontentsadjusteconomy_bottomtier( var_0, var_7 );
                    else if ( isdefined( level.toppercentagetoadjusteconomy ) && var_9 > level.toppercentagetoadjusteconomy )
                        var_7 = lootcontentsadjusteconomy_toptier( var_0, var_7 );
                }
            }

            if ( isdefined( level.maxaccesscardspawns_red ) )
                var_7 = lootcontentsadjust_accesscardsred( var_7 );

            if ( var_0.type != "br_reusable_loot_cache" )
                var_6 = undefined;

            var_5 = var_0 lootcachespawncontents( var_7, var_6 );
        }
        else
        {
            var_10 = ( 0, 0, 0 );
            var_11 = "mp/loot_set_cache_contents_base.csv";

            if ( getdvarint( "scr_br_alt_mode_cash", 0 ) )
                var_11 = "mp/loot_set_cache_contents_base_cash.csv";
            else if ( getdvarint( "scr_br_alt_mode_gg", 0 ) )
                var_11 = "mp/loot_set_cache_contents_base_gg.csv";
            else if ( getdvar( "scr_br_gametype", "" ) == "dmz" || getdvar( "scr_br_gametype", "" ) == "risk" )
            {
                var_10 = ( 0, 45, 0 );

                if ( var_0.type == "br_loot_cache_lege" )
                    var_11 = "mp/loot_set_cache_contents_lege_dmz_ground_tablets.csv";
                else if ( var_0.type == "br_loot_cache" )
                    var_11 = "mp/loot_set_cache_contents_rare_dmz_ground_tablets.csv";
            }

            var_12 = var_0 chooseandspawnitems( 2, 1, "weapon", var_11, var_10 );
            var_5[var_5.size] = var_12[0];
            var_12 = var_0 chooseandspawnitems( 0, 1, "ammo", var_11, var_10 );
            var_5[var_5.size] = var_12[0];
            var_12 = var_0 chooseandspawnitems( 0, 1, undefined, var_11, var_10 );
            var_5[var_5.size] = var_12[0];
            var_12 = var_0 chooseandspawnitems( 0, 1, undefined, var_11, var_10 );
            var_5[var_5.size] = var_12[0];
            var_12 = var_0 chooseandspawnitems( 2, 1, "plunder", var_11, var_10 );
            var_5[var_5.size] = var_12[0];
            var_0 setscriptablepartstate( var_1, "open" );
        }

        var_13 = "cache";

        switch ( var_0.type )
        {
            case "br_loot_cache_lege":
                var_13 = "cache_legendary";
                break;
            case "br_scavenger_quest_cache":
                var_13 = "cache_scavenger";
                break;
            case "br_secretstash_quest_cache":
                var_13 = "cache_secretstash";
                break;
            case "br_geiger_quest_cache":
                var_13 = "cache_geigerstash";
                break;
            case "br_reusable_loot_cache":
                var_0 thread closeagain( var_1 );
                break;
        }

        foreach ( var_15 in var_5 )
            var_15.lootsource = var_13;

        scripts\mp\gametypes\br_plunder.gsc::modify_plunder_itemsinworld( "br_loot_cache", -1 );
        var_3 thread scripts\mp\utility\points::giveunifiedpoints( "br_cacheOpen" );
        var_3 scripts\cp_mp\challenges::oncacheopen();

        if ( !isdefined( var_3.lootcachesopened ) )
            var_3.lootcachesopened = 1;
        else
            var_3.lootcachesopened++;

        var_3 scripts\mp\utility\stats::setextrascore1( var_3.lootcachesopened );

        if ( istrue( level.halloweendvar ) )
            var_3 thread scripts\mp\holiday\halloween.gsc::openbox( var_0.type, var_0, var_3.calloutarea );

        level notify( "lootcache_opened_kill_callout" + var_0.origin );
    }
}

lootcontentsadjusteconomy_bottomtier( var_0, var_1 )
{
    var_2 = [];

    foreach ( var_4 in var_1 )
    {
        if ( issubstr( var_4, "brloot_plunder" ) )
        {
            if ( var_0.type == "br_loot_cache_lege" )
            {
                if ( var_4 != "brloot_plunder_cash_legendary_1" && scripts\engine\utility::cointoss() )
                    var_4 = "brloot_plunder_cash_legendary_1";
            }
            else if ( var_4 != "brloot_plunder_cash_epic_2" && scripts\engine\utility::cointoss() )
                var_4 = "brloot_plunder_cash_epic_2";
        }

        var_2[var_2.size] = var_4;
    }

    return var_2;
}

lootcontentsadjusteconomy_toptier( var_0, var_1 )
{
    var_2 = [];

    foreach ( var_4 in var_1 )
    {
        if ( issubstr( var_4, "brloot_plunder" ) )
        {
            if ( var_0.type == "br_loot_cache_lege" )
            {
                if ( ( var_4 == "brloot_plunder_cash_epic_2" || var_4 == "brloot_plunder_cash_legendary_1" ) && scripts\engine\utility::cointoss() )
                    var_4 = "brloot_plunder_cash_epic_1";
            }
            else if ( ( var_4 == "brloot_plunder_cash_epic_2" || var_4 == "brloot_plunder_cash_epic_1" ) && scripts\engine\utility::cointoss() )
                var_4 = "brloot_plunder_cash_rare_2";
        }

        var_2[var_2.size] = var_4;
    }

    return var_2;
}

lootcontentsadjust_accesscardsred( var_0 )
{
    var_1 = [];

    foreach ( var_3 in var_0 )
    {
        if ( var_3 != "brloot_access_card_red" )
        {
            var_1[var_1.size] = var_3;
            continue;
        }

        if ( level.maxaccesscardspawns_red > level.accesscardsspawned_red )
        {
            var_1[var_1.size] = var_3;
            level.accesscardsspawned_red++;
        }
    }

    return var_1;
}

chooseandspawnitems( var_0, var_1, var_2, var_3, var_4 )
{
    var_5 = [];
    var_6 = 0;

    if ( !isdefined( var_2 ) )
        var_2 = "";

    if ( !isdefined( var_0 ) )
        var_0 = 0;

    var_7 = "mp/loot_set_cache_contents_base.csv";

    if ( isdefined( var_3 ) )
        var_7 = var_3;

    for ( var_8 = 0; var_8 < var_1; var_8++ )
    {
        var_9 = pickscriptablelootitem( var_2, var_0, 0, var_7 );

        if ( canspawnitemname( var_9 ) )
        {
            var_10 = self.angles;

            if ( isdefined( var_4 ) )
                var_10 = var_10 + var_4;

            var_11 = level.br_pickups.br_itemrarity[var_9];

            if ( isdefined( var_11 ) && var_11 == 4 && var_6 == 0 )
            {
                var_5[var_5.size] = lootspawnitem( var_9, self.itemsdropped, self.origin, var_10, undefined, 1 );
                self.itemsdropped++;
                var_6 = 1;
            }
            else
            {
                var_5[var_5.size] = lootspawnitem( var_9, self.itemsdropped, self.origin, var_10, undefined, 0 );
                self.itemsdropped++;
            }
        }
    }

    return var_5;
}

lootcontentsadjustkillchain( var_0, var_1 )
{
    if ( !isdefined( var_1.brkillchainchance ) )
        var_1.brkillchainchance = 10;

    var_2 = 0;

    foreach ( var_5, var_4 in var_0 )
    {
        if ( issubstr( var_4, "killstreak" ) )
        {
            var_2 = 1;
            break;
        }
    }

    if ( !var_2 )
    {
        var_6 = var_1.killcountthislife * 0;

        if ( randomint( 100 ) < var_1.brkillchainchance + var_6 )
        {
            var_7 = [ "brloot_killstreak_clusterstrike", "brloot_killstreak_precision_airstrike", "brloot_killstreak_uav", "brloot_killstreak_shieldturret" ];
            var_0[var_0.size] = scripts\engine\utility::random( var_7 );
            var_1.brkillchainchance = 10;
        }
        else
            var_1.brkillchainchance = var_1.brkillchainchance + ( var_6 + 15 );
    }

    return var_0;
}

lootcontentsadjustdebug( var_0, var_1 )
{
    foreach ( var_3 in level.brlootcache_debuglootitems )
    {
        if ( var_3.prob > randomfloat( 1.0 ) )
            var_0[var_0.size] = var_3.name;
    }

    return var_0;
}

lootcontentsadjustplunder( var_0, var_1 )
{
    var_2 = getdvarfloat( "scr_br_plunder_adjust_prob", 0.8 );

    if ( randomfloat( 1.0 ) < var_2 && !itemscontainplunder( var_0 ) )
    {
        if ( !var_1 squadhasplundertorevive() )
            var_0[var_0.size] = "brloot_plunder_cash_uncommon_1";
    }

    return var_0;
}

itemscontainplunder( var_0 )
{
    foreach ( var_2 in var_0 )
    {
        if ( issubstr( var_2, "brloot_plunder" ) )
            return 1;
    }

    return 0;
}

squadhasplundertorevive()
{
    var_0 = self;

    if ( !isalive( var_0 ) )
        return 0;

    var_1 = 0;
    var_2 = 0;
    var_3 = scripts\mp\utility\teams::getteamdata( var_0.team, "players" );

    foreach ( var_5 in var_3 )
    {
        if ( var_5 scripts\mp\gametypes\br_public.gsc::iseligibleforteamrevive() )
        {
            var_2 = 1;
            continue;
        }

        if ( isdefined( var_5.plundercount ) )
            var_1 = var_1 + var_5.plundercount;
    }

    var_7 = level.br_armory_kiosk.teamrevivefiresalediscount;
    var_8 = var_0 scripts\mp\utility\perk::_hasperk( "specialty_br_cheaper_kiosk" );
    var_9 = level.br_armory_kiosk.teamreviveperkdiscount;

    if ( !isdefined( var_9 ) )
        var_9 = 0;

    var_10 = scripts\mp\gametypes\br_armory_kiosk.gsc::_getactualcost( level.br_armory_kiosk.teamrevivecost, 0, var_7, var_8, var_9 );

    if ( var_2 && isdefined( var_10 ) && var_1 < var_10 )
        return 0;

    return 1;
}
