// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    if ( scripts\mp\utility\game::getgametype() != "br" )
        return;

    _id_11DDF( "br_mastery_fiveContracts", ::lastweaponfiretimeend );
    _id_11DDF( "br_mastery_pointBlank_airstrike", ::_id_11AF3 );
    _id_11DDF( "br_mastery_pointBlank_tomahawk", ::_id_11AF4 );
    _id_11DDF( "br_mastery_c4VehicleMultKill", ::deletescriptableinstanceaftertime_proc );
    _id_11DDF( "br_mastery_ghostRideWhip", ::original_disablelongdeath );
    _id_11DDF( "br_mastery_roundKillExecute", ::_id_12057 );
    _id_11DDF( "br_mastery_travelogue", ::_id_12DE5 );
}

_id_11DDF( var_0, var_1 )
{
    if ( !isdefined( level.circle_speed ) )
        level.circle_speed = [];

    level.circle_speed[var_0] = var_1;
}

droppoint( var_0, var_1 )
{
    if ( !isdefined( level.circle_speed ) )
        return;

    if ( istrue( level.dummy_backpack ) )
        return;

    var_2 = level.circle_speed[var_0];

    if ( isdefined( var_2 ) )
        self thread [[ var_2 ]]( var_0, var_1 );
}

brrebirth_initpostmain( var_0 )
{
    if ( getdvarint( "scr_br_challenge_debug", 0 ) )
        iprintlnbold( "Mastery Challenge: " + var_0 + " completed!" );

    scripts\cp\helicopter\chopper_boss::tv_station_intro_camera( var_0 );
}

sstablet_init( var_0 )
{
    if ( !isdefined( level.teamdata[var_0] ) )
        return;

    foreach ( var_2 in level.teamdata[var_0]["players"] )
        _id_12DE4( var_2 );

    if ( getdvarint( "scr_br_core_trios_or_quads", 0 ) )
    {
        _id_13025( var_0 );
        trackendangeredobjs( var_0 );
    }
}

_id_13025( var_0 )
{
    if ( !isdefined( var_0 ) )
        return;

    var_1 = 0;
    var_2 = 0;
    var_3 = max( 1, level.maxteamsize );

    foreach ( var_5 in level.teamdata[var_0]["players"] )
    {
        var_1 = var_1 + var_5.deaths;

        if ( isdefined( var_5.stealthtimeelapsed ) )
            var_1 = var_1 + var_5.stealthtimeelapsed;

        if ( scripts\mp\utility\player::isreallyalive( var_5 ) )
            var_2++;
    }

    if ( var_1 == 0 )
    {
        foreach ( var_5 in level.teamdata[var_0]["players"] )
            var_5 brrebirth_initpostmain( "br_mastery_untouchable" );
    }
}

trackedtanks()
{
    if ( !isdefined( self ) || !isdefined( self.team ) )
        return;

    var_0 = self.deaths;
    var_1 = self.team;

    foreach ( var_3 in level.teamdata[var_1]["players"] )
    {
        if ( scripts\mp\utility\player::isreallyalive( var_3 ) )
        {
            if ( !isdefined( var_3.stealthtimeelapsed ) )
                var_3.stealthtimeelapsed = 0;

            var_3.stealthtimeelapsed = var_3.stealthtimeelapsed + var_0;
            break;
        }
    }
}

trackendangeredobjs( var_0 )
{
    var_1 = 7;

    if ( !isdefined( var_0 ) )
        return;

    if ( scripts\mp\gametypes\br.gsc::scavenger_cache_hint() )
        return;

    var_2 = 0;

    foreach ( var_4 in level.teamdata[var_0]["players"] )
    {
        var_2 = var_2 + var_4.deaths;

        if ( isdefined( var_4.stealthtimeelapsed ) )
            var_2 = var_2 + var_4.stealthtimeelapsed;
    }

    if ( var_2 >= var_1 )
    {
        foreach ( var_4 in level.teamdata[var_0]["players"] )
            var_4 brrebirth_initpostmain( "br_mastery_neverSayDie" );
    }
}

lastweaponfiretimeend( var_0, var_1 )
{
    if ( !isdefined( self.team ) )
        return;

    if ( scripts\mp\gametypes\br.gsc::get_int_or_0( self.create_trophy_station ) < 5 )
        return;

    var_2 = isdefined( level.gulag ) && !istrue( level.gulag.shutdown );

    foreach ( var_4 in level.teamdata[self.team]["players"] )
    {
        if ( !scripts\mp\utility\player::isreallyalive( var_4 ) )
            return;

        if ( var_2 && var_4 scripts\mp\gametypes\br_public.gsc::rungwperif_flak() )
            return;
    }

    brrebirth_initpostmain( var_0 );
}

_id_11AF3( var_0, var_1 )
{
    var_2 = var_1.wait_for_tank_death;
    var_3 = var_1._id_12BB8;

    if ( !isdefined( var_2 ) || !isdefined( var_2.binoculars_onstatemarkpendingupdate ) || !isdefined( var_2.streakinfo ) || !isdefined( var_3 ) )
        return;

    var_4 = var_2.streakinfo;

    if ( distancesquared( self.origin, var_3 ) > squared( 432 ) )
        return;

    self endon( "death_or_disconnect" );
    self notify( "pointBlank_airstrike_killtracker" );
    self endon( "pointBlank_airstrike_killtracker" );
    scripts\engine\utility::_id_13403( 10.0, "airstrike_finished_" + var_2.binoculars_onstatemarkpendingupdate );

    if ( !scripts\mp\utility\player::isreallyalive( self ) )
        return;

    if ( var_4.kills >= 3 )
        brrebirth_initpostmain( "br_mastery_pointBlankStreakKill" );
}

_id_11AF4( var_0, var_1 )
{
    var_2 = var_1.streakinfo;
    var_3 = var_1._id_12BB8;

    if ( !isdefined( var_2 ) )
        return;

    if ( !isdefined( var_3 ) )
        return;

    if ( distancesquared( self.origin, var_3 ) > squared( 432 ) )
        return;

    self endon( "death_or_disconnect" );
    self notify( "pointBlank_tomahawk_killtracker" );
    self endon( "pointBlank_tomahawk_killtracker" );
    scripts\engine\utility::_id_13404( 20, "cluster_strike_finished" );

    if ( !scripts\mp\utility\player::isreallyalive( self ) )
        return;

    if ( var_2.kills >= 3 )
        brrebirth_initpostmain( "br_mastery_pointBlankStreakKill" );

    return;
}

deletescriptableinstanceaftertime_proc( var_0, var_1 )
{
    var_2 = var_1.meansofdeath;
    var_3 = var_1.inflictor;

    if ( !isdefined( var_2 ) || var_2 != "MOD_EXPLOSIVE" )
        return;

    if ( !score_message( var_3 ) )
        return;

    self endon( "disconnect" );
    level endon( "game_ended" );
    self notify( "updateC4VehicleMultKill" );
    self endon( "updateC4VehicleMultKill" );

    if ( !isdefined( self._id_11D66 ) )
        self._id_11D66 = 0;

    self._id_11D66++;
    wait 4.0;

    if ( isdefined( self._id_11D66 ) && self._id_11D66 >= 3 )
    {
        brrebirth_initpostmain( var_0 );
        var_4 = deletescriptableinstanceaftertime( var_3 );
        var_5 = isdefined( var_4 ) && isdefined( var_4.team ) && isdefined( self.team ) && var_4.team == self.team;

        if ( var_5 )
            var_4 brrebirth_initpostmain( var_0 );
    }

    self._id_11D66 = undefined;
}

score_message( var_0 )
{
    if ( !isdefined( var_0 ) )
        return 0;

    if ( isdefined( var_0.vehiclename ) && !var_0 scripts\common\vehicle_code::vehicle_is_stopped() )
    {
        var_1 = var_0 getlinkedchildren();

        foreach ( var_3 in var_1 )
        {
            if ( isdefined( var_3.weapon_name ) && var_3.weapon_name == "c4_mp_p" )
                return 1;
        }
    }
    else if ( isdefined( var_0.weapon_name ) && var_0.weapon_name == "c4_mp_p" )
    {
        var_5 = var_0 getlinkedparent();

        if ( isdefined( var_5 ) && isdefined( var_5.vehiclename ) && !var_5 scripts\common\vehicle_code::vehicle_is_stopped() )
            return 1;
    }

    return 0;
}

deletescriptableinstanceaftertime( var_0 )
{
    if ( isdefined( var_0 ) && isdefined( var_0.weapon_name ) && var_0.weapon_name == "c4_mp_p" )
    {
        var_1 = var_0 getlinkedparent();

        if ( isdefined( var_1 ) )
            return var_1.owner;
    }

    return undefined;
}

_id_12057( var_0, var_1 )
{
    var_2 = var_1.player;

    if ( !isdefined( var_2 ) )
        return;

    if ( isdefined( var_2.modifiers["execution"] ) && var_2.modifiers["execution"] == 1 )
        var_2 brrebirth_initpostmain( "br_mastery_roundKillExecute" );
}

original_disablelongdeath( var_0, var_1 )
{
    self endon( "disconnect" );
    level endon( "game_ended" );

    if ( !isdefined( self ) )
        return;

    var_2 = var_1.isusingremotekillstreak;
    var_3 = var_1.spawnangle;

    if ( istrue( var_2 ) )
    {
        if ( istrue( self.player_helis ) && self._id_11D67 != 0 )
            return;

        self.player_helis = 1;
    }

    if ( !istrue( self.player_helis ) )
        return;

    self notify( "ghostRideWhip" );
    self endon( "ghostRideWhip" );

    if ( !isdefined( self._id_11D67 ) )
        self._id_11D67 = 0;

    if ( istrue( var_3 ) )
        self._id_11D67++;

    wait 4.0;

    if ( !isdefined( self ) )
        return;

    if ( isdefined( self._id_11D67 ) && self._id_11D67 >= 3 )
        brrebirth_initpostmain( var_0 );

    self._id_11D67 = undefined;
    self.player_helis = undefined;
}

_id_12DE5( var_0, var_1 )
{
    var_2 = -1;

    if ( getdvarint( "scr_br_core_trios_or_quads", 0 ) == 0 )
        return;

    var_3 = var_1.inflictor;

    if ( !isdefined( var_3 ) )
        return;

    if ( !isplayer( var_3 ) && isdefined( var_3.owner ) && isplayer( var_3.owner ) )
        var_3 = var_3.owner;
    else
        return;

    var_4 = var_1.victim;

    if ( !isdefined( var_4 ) || !isplayer( var_4 ) )
        return;

    var_5 = 0;
    var_6 = var_3 scripts\mp\gametypes\br_callouts.gsc::nuke_killplayerwithattacker( var_3 );

    if ( var_6 != var_2 )
        var_5 = var_5 | 1 << var_6;

    var_6 = var_4 scripts\mp\gametypes\br_callouts.gsc::nuke_killplayerwithattacker( var_4 );

    if ( var_6 != var_2 )
        var_5 = var_5 | 1 << var_6;

    if ( var_5 == 0 )
        return;

    foreach ( var_8 in level.teamdata[var_3.team]["players"] )
    {
        if ( !isdefined( var_8._id_13731 ) )
            var_8._id_13731 = 0;

        var_8._id_13731 = var_8._id_13731 | var_5;
    }
}

_id_12DE4( var_0 )
{
    var_1 = 12;

    if ( !isdefined( var_0._id_13731 ) || var_0._id_13731 == 0 )
        return;

    var_2 = 0;

    for ( var_3 = 0; var_3 < level.calloutglobals.tr_entergulag.size; var_3++ )
    {
        var_4 = var_0._id_13731 & 1 << var_3;

        if ( var_4 )
            var_2++;
    }

    if ( var_2 >= var_1 )
        var_0 brrebirth_initpostmain( "br_mastery_travelogue" );

    return;
}
