// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    if ( !getdvarint( "scr_br_gxp_fear", 0 ) )
        return;

    level.completesmokinggunquest.play_operator_reply_vo = [];
    level.completesmokinggunquest.play_nuclear_core_vo = [];
    level.completesmokinggunquest.play_nuclear_core_vo[1] = [];
    level.completesmokinggunquest.play_nuclear_core_vo[2] = [];
    level.completesmokinggunquest.play_nuclear_core_vo[3] = [];
    level._effect["vfx_gxp_flies_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_flies_minor.vfx" );
    level._effect["vfx_gxp_flies_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_flies_major.vfx" );
    level._effect["vfx_gxp_eyes_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_eyes_minor.vfx" );
    level._effect["vfx_gxp_eyes_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_eyes_major.vfx" );
    level._effect["vfx_gxp_mosquitos_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_mosquitos_minor.vfx" );
    level._effect["vfx_gxp_mosquitos_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_mosquitos_major.vfx" );
    level._effect["vfx_gxp_heatdist_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_heatdist_minor.vfx" );
    level._effect["vfx_gxp_heatdist_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_heatdist_major.vfx" );
    level._effect["vfx_gxp_skulls_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_skulls_major.vfx" );
    level._effect["vfx_gxp_skulls_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_skulls_minor.vfx" );
    level._effect["vfx_gxp_molotov_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_molotov_minor.vfx" );
    level._effect["vfx_gxp_tracers_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_tracers_minor.vfx" );
    level._effect["vfx_gxp_tracers_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_tracers_major.vfx" );
    level._effect["vfx_ghost_death_3p"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_ghost_death_3p.vfx" );
    level._effect["vfx_gxp_chest_bluefire_death"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_chest_bluefire_death.vfx" );
    level._effect["vfx_gxp_corpuscules_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_corpuscules_minor.vfx" );
    level._effect["vfx_gxp_corpuscules_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_corpuscules_major.vfx" );
    level._effect["vfx_gxp_cracks_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_cracks_minor.vfx" );
    level._effect["vfx_gxp_cracks_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_cracks_major.vfx" );
    level._effect["vfx_gxp_meatholes_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_meatholes_minor.vfx" );
    level._effect["vfx_gxp_meatholes_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_meatholes_major.vfx" );
    level._effect["vfx_gxp_splatter_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_splatter_minor.vfx" );
    level._effect["vfx_gxp_splatter_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_splatter_major.vfx" );
    level._effect["vfx_gxp_rainbows_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_rainbows_minor.vfx" );
    level._effect["vfx_gxp_rainbows_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_rainbows_major.vfx" );
    level._effect["vfx_gxp_crescents_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_crescents_minor.vfx" );
    level._effect["vfx_gxp_crescents_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_crescents_major.vfx" );
    level._effect["vfx_gxp_flames_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_flames_minor.vfx" );
    level._effect["vfx_gxp_flames_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_flames_major.vfx" );
    level._effect["vfx_gxp_wiggler_01_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_wiggler_01_minor.vfx" );
    level._effect["vfx_gxp_wiggler_01_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_wiggler_01_major.vfx" );
    level._effect["vfx_gxp_splashy_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_splashy_minor.vfx" );
    level._effect["vfx_gxp_splashy_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_splashy_major.vfx" );
    level._effect["vfx_gxp_streakwiggle_01_major"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_streakwiggle_01_major.vfx" );
    level._effect["vfx_gxp_streakwiggle_01_minor"] = loadfx( "vfx/iw8_br/gameplay/hween2/vfx_gxp_streakwiggle_01_minor.vfx" );
    level.completesmokinggunquest.play_loop_nagging_hostage_on_convoy = spawn( "script_model", ( 0, 0, 0 ) );
    initvalues();
    addhallucinationtiers();
    recondronemarkedcb();
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_flies_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_flies_minor", _id_1244C( 0, 4, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_flies_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_flies_major", _id_1244C( 0, 5, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_eyes_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_eyes_minor", _id_1244C( 0, 4, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_eyes_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_eyes_major", _id_1244C( 0, 5, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_mosquitos_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_mosquitos_minor", _id_1244C( 0, 3, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_mosquitos_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_mosquitos_major", _id_1244C( 0, 4, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_heatdist_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_heatdist_minor", _id_1244C( 0, 3, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_heatdist_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_heatdist_major", _id_1244C( 0, 4, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_skulls_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_skulls_minor", _id_1244C( 0, 2.5, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_skulls_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_skulls_major", _id_1244C( 0, 3, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_corpuscules_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_corpuscules_minor", _id_1244C( 0, 3, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_corpuscules_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_corpuscules_major", _id_1244C( 0, 4, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_cracks_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_cracks_minor", _id_1244C( 0, 4, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_cracks_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_cracks_major", _id_1244C( 0, 5, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_meatholes_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_meathole_minor", _id_1244C( 0, 2, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_meatholes_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_meathole_major", _id_1244C( 0, 2, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_splatter_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_splatter_minor", _id_1244C( 0, 2, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_splatter_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_splatter_major", _id_1244C( 0, 2, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_rainbows_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_rainbows_minor", _id_1244C( 0, 2, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_rainbows_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_rainbows_major", _id_1244C( 0, 2, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_crescents_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_crescents_minor", _id_1244C( 0, 2, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_crescents_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_crescents_major", _id_1244C( 0, 2, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_flames_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_flames_minor", _id_1244C( 0, 2, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_flames_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_flames_major_major", _id_1244C( 0, 2, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_wiggler_01_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_wiggler_01_minor", _id_1244C( 0, 2, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_wiggler_01_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_wiggler_01_major_major", _id_1244C( 0, 2, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_splashy_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_splashy_minor", _id_1244C( 0, 2, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_splashy_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_splashy_major", _id_1244C( 0, 2.5, "fov_medium" ) );
    animscripted_loop( 2, 0.2, ::play_nags_from_array, _id_12480( "vfx_gxp_streakwiggle_01_minor", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_streakwiggle_01_minor", _id_1244C( 0, 2, "fov_low" ) );
    animscripted_loop( 3, 0.3, ::play_nags_from_array, _id_12480( "vfx_gxp_streakwiggle_01_major", 1, 2.5 ), ::spawn_exfil_heli, "scr_br_gxp_disable_hallucination_streakwiggle_01_major", _id_1244C( 0, 2.5, "fov_medium" ) );
    animscripted_loop( 1, 0.1, ::play_nag_players_place_hvt, "br_gov_aural_hallucination", ::spawn_exfil_enemies, "scr_br_gxp_disable_hallucination_aural" );
    animscripted_loop( 1, 0.1, ::play_nag_players_place_hvt, "dx_bra_halu_hallucination_voice", ::spawn_exfil_enemies, "scr_br_gxp_disable_hallucination_halu_voice" );
    animscripted_loop( 1, 0.1, ::play_nag_players_place_hvt, "dx_bra_hal2_hallucination_voice", ::spawn_exfil_enemies, "scr_br_gxp_disable_hallucination_hal2_voice" );
    animscripted_loop( 2, 0.2, ::play_onboard_plane_vo, 5, ::spawn_exfil_chopper, "scr_br_gxp_disable_hallucination_scramble_hud_median" );
    animscripted_loop( 3, 0.3, ::play_onboard_plane_vo, 15, ::spawn_exfil_chopper, "scr_br_gxp_disable_hallucination_scramble_hud_major" );
    animscripted_loop( 2, 0.2, ::play_lz_vo, killstreak_loadout_state( 2, 0.7, 1.2, 40, 0 ), ::spawn_enemy_drone_turret, "scr_br_gxp_disable_hallucination_fake_damage_median" );
    animscripted_loop( 3, 0.3, ::play_lz_vo, killstreak_loadout_state( 5, 0.7, 1.5, 60, 0 ), ::spawn_enemy_drone_turret, "scr_br_gxp_disable_hallucination_fake_damage_major" );
    animscripted_loop( 2, 0.2, ::play_music_to_team, _id_1243D( 11, "ta_gov_01", 4.26, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_01" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 12, "ta_gov_02", 5.0, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_02" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 13, "ta_gov_03", 5.0, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_03" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 14, "ta_gov_04", 4.1, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_04" );
    animscripted_loop( 2, 0.2, ::play_music_to_team, _id_1243D( 15, "ta_gov_05", 5.0, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_05" );
    animscripted_loop( 2, 0.2, ::play_music_to_team, _id_1243D( 16, "ta_gov_06", 5.0, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_06" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 17, "ta_gov_07", 5.0, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_07" );
    animscripted_loop( 2, 0.2, ::play_music_to_team, _id_1243D( 18, "ta_gov_08", 5.0, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_08" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 19, "ta_gov_09", 5.06, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_09" );
    animscripted_loop( 2, 0.2, ::play_music_to_team, _id_1243D( 20, "ta_gov_10", 5.01, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_10" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 21, "ta_gov_11", 3.11, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_11" );
    animscripted_loop( 2, 0.2, ::play_music_to_team, _id_1243D( 22, "ta_gov_12", 5.01, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_12" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 23, "ta_gov_13", 3.23, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_13" );
    animscripted_loop( 2, 0.2, ::play_music_to_team, _id_1243D( 24, "ta_gov_14", 5.16, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_14" );
    animscripted_loop( 2, 0.2, ::play_music_to_team, _id_1243D( 25, "ta_gov_15", 5.19, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_15" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 26, "ta_gov_16", 5.24, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_16" );
    animscripted_loop( 2, 0.2, ::play_music_to_team, _id_1243D( 27, "ta_gov_17", 5.02, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_17" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 28, "ta_gov_18", 2.39, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_18" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 29, "ta_gov_19", 4.6, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_19" );
    animscripted_loop( 2, 0.2, ::play_music_to_team, _id_1243D( 30, "ta_gov_20", 5.2, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_20" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 31, "ta_gov_21", 6.2, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_21" );
    animscripted_loop( 3, 0.3, ::play_music_to_team, _id_1243D( 32, "ta_gov_22", 6.2, 1 ), ::spawn_enemy_claymore, "scr_br_gxp_disable_hallucination_22" );
    _id_12563();
}

initvalues()
{
    level.completesmokinggunquest.fearval.corpsevfxradius = getdvarint( "scr_fear_corpse_vfx_radius", 10000 );
    level.completesmokinggunquest.fearval.corpsevfxobserverms = getdvarint( "scr_fear_corpse_vfx_observer_ms", 5000 );
    level.completesmokinggunquest.fearval.playervfxradius = getdvarint( "scr_fear_player_vfx_radius", 1000 );
    level.completesmokinggunquest.fearval.playervfxobservermsmin = getdvarint( "scr_fear_player_vfx_observer_ms_min", 30000 );
    level.completesmokinggunquest.fearval.playervfxobservermsmax = getdvarint( "scr_fear_player_vfx_observer_ms_max", 90000 );
}

addhallucinationtiers()
{
    var_0 = ( 1, 0, 0 );
    var_1 = ( 1, 1, 0 );
    var_2 = ( 0, 1, 0 );
    var_3 = getdvarfloat( "scr_hallucination_trigger_3", 0.75 );
    var_4 = getdvarfloat( "scr_fear_tier3_tas", 25 );
    var_5 = getdvarfloat( "scr_fear_tier3_tae", 15 );
    var_6 = getdvarfloat( "scr_fear_tier3_tv", 5 );
    var_7 = getdvarfloat( "scr_fear_tier3_ns", 0.0 );
    var_8 = getdvarfloat( "scr_fear_tier3_ne", 0.0 );
    var_9 = getdvarfloat( "scr_fear_tier3_mins", 0.0 );
    var_10 = getdvarfloat( "scr_fear_tier3_mine", 0.0 );
    var_11 = getdvarfloat( "scr_fear_tier3_meds", 0.1 );
    var_12 = getdvarfloat( "scr_fear_tier3_mede", 0.1 );
    var_13 = getdvarfloat( "scr_fear_tier3_majs", 0.9 );
    var_14 = getdvarfloat( "scr_fear_tier3_maje", 0.9 );
    _id_12451( var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11, var_12, var_13, var_14, var_0 );
    var_3 = getdvarfloat( "scr_hallucination_trigger_2", 0.5 );
    var_4 = getdvarfloat( "scr_fear_tier2_tas", 30 );
    var_5 = getdvarfloat( "scr_fear_tier2_tae", 20 );
    var_6 = getdvarfloat( "scr_fear_tier2_tv", 5 );
    var_7 = getdvarfloat( "scr_fear_tier2_ns", 0.2 );
    var_8 = getdvarfloat( "scr_fear_tier2_ne", 0.2 );
    var_9 = getdvarfloat( "scr_fear_tier2_mins", 0.2 );
    var_10 = getdvarfloat( "scr_fear_tier2_mine", 0.2 );
    var_11 = getdvarfloat( "scr_fear_tier2_meds", 0.6 );
    var_12 = getdvarfloat( "scr_fear_tier2_mede", 0.6 );
    var_13 = getdvarfloat( "scr_fear_tier2_majs", 0.2 );
    var_14 = getdvarfloat( "scr_fear_tier2_maje", 0.2 );
    _id_12451( var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11, var_12, var_13, var_14, var_0 );
    var_3 = getdvarfloat( "scr_hallucination_trigger_1", 0.0 );
    var_4 = getdvarfloat( "scr_fear_tier1_tas", 40 );
    var_5 = getdvarfloat( "scr_fear_tier1_tae", 30 );
    var_6 = getdvarfloat( "scr_fear_tier1_tv", 10 );
    var_7 = getdvarfloat( "scr_fear_tier1_ns", 0.4 );
    var_8 = getdvarfloat( "scr_fear_tier1_ne", 0.4 );
    var_9 = getdvarfloat( "scr_fear_tier1_mins", 0.8 );
    var_10 = getdvarfloat( "scr_fear_tier1_mine", 0.8 );
    var_11 = getdvarfloat( "scr_fear_tier1_meds", 0.2 );
    var_12 = getdvarfloat( "scr_fear_tier1_mede", 0.2 );
    var_13 = getdvarfloat( "scr_fear_tier1_majs", 0.0 );
    var_14 = getdvarfloat( "scr_fear_tier1_maje", 0.0 );
    _id_12451( var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11, var_12, var_13, var_14, var_0 );
}

recondronemarkedcb()
{

}

onplayerconnect( var_0 )
{
    var_0.open_doors = [];

    foreach ( var_3, var_2 in level.completesmokinggunquest.play_nuclear_core_vo )
    {
        if ( var_2.size )
            var_0.open_doors[var_3] = randomint( var_2.size );
    }
}

onplayerspawned()
{
    if ( !level.completesmokinggunquest.kstargetlocation )
        return;

    farah_nobraids_body_reset();
}

_id_12451( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11, var_12 )
{
    var_13 = spawnstruct();
    var_13._id_12E89 = var_0;
    var_13.time = ( var_1, var_2, var_3 );
    var_13.get_smallest_cumulative_damage = 0.0;
    var_14 = 1.0 - var_4;
    var_15 = 1.0 - var_5;
    var_13.play_intro_hacking_vo = [];
    var_13.play_intro_hacking_vo[0] = ( var_4, var_5, 0 );
    var_13.play_intro_hacking_vo[1] = ( var_6 * var_14, var_7 * var_15, 0 );
    var_13.play_intro_hacking_vo[2] = ( var_8 * var_14, var_9 * var_15, 0 );
    var_13.play_intro_hacking_vo[3] = ( var_10 * var_14, var_11 * var_15, 0 );
    var_13.haspassedsquadleader = var_12;
    level.completesmokinggunquest.play_operator_reply_vo[level.completesmokinggunquest.play_operator_reply_vo.size] = var_13;
}

destroy_jammer_relocate()
{
    foreach ( var_1 in level.completesmokinggunquest.play_operator_reply_vo )
        var_1.get_smallest_cumulative_damage = randomfloatrange( -1 * var_1.time[2], var_1.time[2] );
}

nexttrackindex( var_0 )
{
    foreach ( var_3, var_2 in level.completesmokinggunquest.play_operator_reply_vo )
    {
        if ( var_2._id_12E89 <= var_0 )
            return var_3;
    }

    return 0;
}

onplant()
{
    var_0 = level.completesmokinggunquest.play_operator_reply_vo[self.play_animation_old]._id_12E89;
    var_1 = 1.0;

    if ( self.play_animation_old > 0 )
        var_1 = level.completesmokinggunquest.play_operator_reply_vo[self.play_animation_old - 1]._id_12E89;

    var_2 = ( self.play_alert_music_to_player - var_0 ) / ( var_1 - var_0 );
    return var_2;
}

_id_1243D( var_0, var_1, var_2, var_3, var_4 )
{
    var_5 = spawnstruct();
    var_5.length = var_2;
    var_5.cinematic = var_1;
    var_5.initplunderpads = var_3;
    var_5.index = var_0;
    var_5._id_11A8B = var_4;
    return var_5;
}

_id_12480( var_0, var_1, var_2 )
{
    var_3 = spawnstruct();
    var_3.fx = var_0;
    var_3._id_11A8B = var_1;
    var_3.length = var_2;
    return var_3;
}

_id_1244C( var_0, var_1, var_2 )
{
    var_3 = spawnstruct();
    var_3.setupstartweaponsattachments = var_0;
    var_3.length = var_1;
    var_3.type = var_2;
    return var_3;
}

animscripted_loop( var_0, var_1, var_2, var_3, var_4, var_5, var_6 )
{
    if ( getdvarint( var_5, 0 ) )
        return;

    var_7 = spawnstruct();
    var_7.ks_killleaders = var_1;
    var_7.function = var_2;
    var_7.spawn_carried_punchcard_if_player_down = var_4;
    var_7.data = var_3;
    var_7.little_bird_mg_mp_enterendinternal = var_6;
    level.completesmokinggunquest.play_nuclear_core_vo[var_0][level.completesmokinggunquest.play_nuclear_core_vo[var_0].size] = var_7;
}

_id_12563()
{
    foreach ( var_2, var_1 in level.completesmokinggunquest.play_nuclear_core_vo )
        level.completesmokinggunquest.play_nuclear_core_vo[var_2] = scripts\engine\utility::array_randomize( var_1 );
}

vipbot_movesup( var_0 )
{
    var_1 = level.completesmokinggunquest.play_operator_reply_vo[self.play_animation_old];
    var_2 = randomfloat( 1 );
    var_3 = 0;
    var_4 = 0;

    for ( var_5 = 0; var_5 < 4; var_5++ )
    {
        if ( var_5 > 0 && level.completesmokinggunquest.play_nuclear_core_vo[var_5].size )
            var_4 = var_5;

        var_3 = var_3 + scripts\engine\math::lerp( var_1.play_intro_hacking_vo[var_5][0], var_1.play_intro_hacking_vo[var_5][1], var_0 );

        if ( var_3 >= var_2 )
            return var_4;
    }
}

vip_respawnplayer( var_0 )
{
    var_1 = undefined;

    if ( isdefined( self.open_doors[var_0] ) )
    {
        var_1 = self.open_doors[var_0] % level.completesmokinggunquest.play_nuclear_core_vo[var_0].size;
        self.open_doors[var_0]++;
    }

    return var_1;
}

update( var_0 )
{
    self endon( "death" );
    self endon( "disconnect" );

    if ( istrue( self.gxp_halluciation_block ) )
        return;

    self.play_alert_music_to_player = var_0;
    self.play_animation_old = nexttrackindex( var_0 );
    var_1 = level.completesmokinggunquest.play_operator_reply_vo[self.play_animation_old];
    var_2 = onplant();
    var_3 = ( scripts\engine\math::lerp( var_1.time[0], var_1.time[1], var_2 ) + var_1.get_smallest_cumulative_damage ) * 1000;

    if ( self.play_animation + var_3 < gettime() )
    {
        var_4 = vipbot_movesup( var_2 );

        if ( var_4 != 0 )
        {
            self.gxp_halluciation_block = 1;
            var_5 = vip_respawnplayer( var_4 );

            if ( isdefined( var_5 ) )
            {
                var_0 = level.completesmokinggunquest.play_nuclear_core_vo[var_4][var_5];
                _id_13080( var_0.little_bird_mg_mp_enterendinternal );
                [[ var_0.function ]]( var_0.data );
                scripts\mp\gametypes\br_gxp_fear.gsc::labelpc( "onPlayerHallucinate", var_0 );
            }
        }
        else
        {

        }

        self.gxp_halluciation_block = 0;
        self.play_animation = gettime();
        destroy_jammer_relocate();
    }
}

_id_13080( var_0 )
{
    if ( getdvarint( "scr_disable_hallucination_fov_shift", 0 ) )
        return;

    if ( !isdefined( var_0 ) )
        return;

    self lerpfovbypreset( "hallucination" );

    if ( var_0.type == "fov_low" )
        self visionsetnakedforplayer( "mp_gxp_fov_low", 1 );
    else
        self visionsetnakedforplayer( "mp_gxp_fov_medium", 1 );

    thread interaction_is_jugg_maze_button( var_0.length );
    thread failsmokinggunquest();

    if ( isdefined( var_0.setupstartweaponsattachments ) && var_0.setupstartweaponsattachments > 0 )
        wait( var_0.setupstartweaponsattachments );
}

farah_nobraids_body_reset()
{
    self.play_animation = gettime();
    self.play_alert_music_to_player = 0;
    self.play_animation_old = 0;
    self.gxp_halluciation_block = 0;
}

play_nag_players_place_hvt( var_0 )
{
    self playsoundtoplayer( var_0, self, self );
    wait 3;
}

play_music_on_wave_reinforce( var_0 )
{
    level thread scripts\mp\gametypes\br_public.gsc::cpcpammoarmorcratecapturecallback( var_0, self, 1 );
    wait 3;
}

play_nag_players_interact_fulton( var_0 )
{
    self setplayermusicstate( var_0 );
    wait 3;
}

play_music_to_team( var_0 )
{
    self endon( "disconnect" );

    if ( istrue( var_0._id_11A8B ) )
        _id_11A5D();

    self setclientomnvar( "ui_halloween_event", var_0.index );
    var_1 = 3;
    wait( var_0.length );
}

play_nags_from_array( var_0 )
{
    self endon( "death" );

    if ( istrue( var_0._id_11A8B ) )
        _id_11A5D();

    playfxontagforclients( scripts\engine\utility::getfx( var_0.fx ), self, "tag_eye", self );
    wait( var_0.length );
}

play_onboard_plane_vo( var_0 )
{
    scripts\cp_mp\emp_debuff::play_emp_scramble( 5 );
    thread fake_model();
    is_ai_facing_point( var_0 );
}

is_ai_facing_point( var_0 )
{
    self endon( "death" );
    self endon( "disconnect" );
    wait( var_0 );
    self notify( "end_scramble_hud" );
    scripts\cp_mp\emp_debuff::stop_emp_scramble( 5 );
}

fake_model()
{
    self endon( "disconnect" );
    self endon( "end_scramble_hud" );
    self waittill( "death" );
    scripts\cp_mp\emp_debuff::stop_emp_scramble( 5 );
}

play_nag_intro_vo( var_0 )
{
    var_1 = onspray( var_0 );

    if ( !isdefined( var_1 ) )
        return;

    var_2 = mp_vacant_patch( var_1.origin );

    if ( !isdefined( var_2 ) )
        return;

    playfxontagforclients( level._effect["vfx_ghost_death_3p"], var_1, "j_spineupper", var_2 );
    var_2 spawn_ending_individual_guys_death( "vfx_ghost_death_3p", "corpsevfx" );
}

onspray( var_0 )
{
    var_1 = gettime();
    var_2 = var_1 + 250;

    for ( var_3 = undefined; isdefined( var_0 ) && var_1 < var_2; var_1 = gettime() )
    {
        var_3 = var_0 getcorpseentity();

        if ( isdefined( var_3 ) )
            return var_3;

        waitframe();
    }

    return undefined;
}

mp_vacant_patch( var_0 )
{
    var_1 = level.completesmokinggunquest.play_landlord_infil_vo;

    if ( isdefined( var_1 ) && var_1 scripts\mp\gametypes\br_gxp_fear.gsc::display_hint_for_player_single() && level.completesmokinggunquest.play_lighting_sequence < gettime() )
    {
        if ( distance2dsquared( var_0, var_1.origin ) > level.completesmokinggunquest.fearval.corpsevfxradius * level.completesmokinggunquest.fearval.corpsevfxradius )
            return undefined;

        var_2 = anglestoforward( var_1.angles );
        var_3 = vectornormalize( var_0 - var_1.origin );

        if ( vectordot( var_2, var_3 ) <= 0 )
            return undefined;

        return var_1;
    }

    var_4 = undefined;

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "player", "getPlayersInRadius" ) )
        var_4 = [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "player", "getPlayersInRadius" ) ]]( var_0, level.completesmokinggunquest.fearval.corpsevfxradius );

    var_4 = scripts\engine\utility::array_randomize( var_4 );

    foreach ( var_1 in var_4 )
    {
        if ( !isalive( var_1 ) || var_1 scripts\mp\gametypes\br_public.gsc::zombie() || !var_1 scripts\mp\gametypes\br_gxp_fear.gsc::display_hint_for_player_single() )
            continue;

        var_2 = anglestoforward( var_1.angles );
        var_3 = vectornormalize( var_0 - var_1.origin );

        if ( vectordot( var_2, var_3 ) <= 0 )
            continue;

        level.completesmokinggunquest.play_landlord_infil_vo = var_1;
        level.completesmokinggunquest.play_lighting_sequence = gettime() + level.completesmokinggunquest.fearval.corpsevfxobserverms;
        return var_1;
    }

    return undefined;
}

tr_playerdisconnect()
{
    for (;;)
    {
        var_0 = scripts\engine\utility::array_randomize( level.players );

        foreach ( var_2 in var_0 )
        {
            if ( !isdefined( var_2 ) || !isalive( var_2 ) || var_2 scripts\mp\gametypes\br_public.gsc::zombie() || !var_2 scripts\mp\gametypes\br_gxp_fear.gsc::display_hint_for_player_single() )
                continue;

            if ( isdefined( var_2.play_nag_players_hvt_callouts ) && var_2.play_nag_players_hvt_callouts > gettime() )
                continue;

            var_3 = nukeplayer( var_2, level.completesmokinggunquest.fearval.playervfxradius );

            if ( isdefined( var_3 ) )
            {
                playfxontagforclients( level._effect["vfx_gxp_chest_bluefire_death"], var_3, "j_spineupper", var_2 );
                var_2.play_nag_players_hvt_callouts = gettime() + randomintrange( level.completesmokinggunquest.fearval.playervfxobservermsmin, level.completesmokinggunquest.fearval.playervfxobservermsmax );
                var_2 spawn_ending_individual_guys_death( "vfx_gxp_chest_bluefire_death", "nearbyplayervfx" );
            }

            waitframe();
        }

        waitframe();
    }
}

play_lz_vo( var_0 )
{
    self endon( "death" );
    var_1 = gettime() + var_0.init_standard_range * 1000;
    var_2 = randomfloat( 360 );
    var_3 = 3000;

    while ( var_1 > gettime() )
    {
        if ( randomfloat( 1 ) < var_0._id_135CF )
            self playsoundtoplayer( "", self );
        else
        {
            var_4 = angleclamp( var_2 + randomfloat( var_0.bot1 ) );
            var_5 = cos( var_4 );
            var_6 = sin( var_4 );
            var_7 = ( var_5, var_6, 0 );
            var_8 = self geteye();
            var_9 = var_8 + var_7 * var_3;
            self playsoundtoplayer( "bullet_small_flesh_torso_plr", self );
            self.donotmodifydamage = 1;
            self dodamage( 1, var_9, level.completesmokinggunquest.play_loop_nagging_hostage_on_convoy );
            self.donotmodifydamage = undefined;
        }

        wait( randomfloatrange( var_0.remove_excluder_ai, var_0.remove_prohibited_weapons ) );
    }
}

killstreak_loadout_state( var_0, var_1, var_2, var_3, var_4 )
{
    var_5 = spawnstruct();
    var_5.init_standard_range = var_0;
    var_5.remove_excluder_ai = var_1;
    var_5.remove_prohibited_weapons = var_2;
    var_5.bot1 = var_3;
    var_5._id_135CF = var_4;
    return var_5;
}

nukeplayer( var_0, var_1 )
{
    var_2 = anglestoforward( var_0.angles );
    var_3 = undefined;

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "player", "getPlayersInRadius" ) )
        var_3 = [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "player", "getPlayersInRadius" ) ]]( var_0.origin, var_1 );

    var_3 = scripts\engine\utility::array_randomize( var_3 );

    foreach ( var_5 in var_3 )
    {
        if ( var_5 == var_0 || var_5 scripts\mp\gametypes\br_public.gsc::zombie() || !isalive( var_5 ) )
            continue;

        var_6 = vectornormalize( var_5.origin - var_0.origin );

        if ( vectordot( var_2, var_6 ) <= 0 )
            continue;

        return var_5;
    }

    return undefined;
}

play_missile_target_marker_vfx_on_missile_target_ent( var_0 )
{
    self lerpfovbypreset( "hallucination" );
    self visionsetnakedforplayer( "mp_gxp_fov_shift", 1 );
    thread failsmokinggunquest();
    interaction_is_jugg_maze_button( var_0 );
}

interaction_is_jugg_maze_button( var_0 )
{
    self endon( "death" );
    self endon( "disconnect" );
    wait( var_0 );
    self notify( "end_fov_hud" );
    self lerpfovbypreset( "default_fast" );
    self visionsetnakedforplayer( "", 2 );
}

failsmokinggunquest()
{
    self endon( "disconnect" );
    self endon( "end_fov_hud" );
    self waittill( "death" );
    self lerpfovbypreset( "default" );
    self visionsetnakedforplayer( "", 0 );
}

_id_11A5D()
{
    self playsoundtoplayer( "br_gov_hallucination_sting", self, self );
    wait 0.1;
}

spawn_ending_individual_guys_death( var_0, var_1 )
{
    var_2 = [];
    var_2[var_2.size] = "time_msfrommatchstart";
    var_2[var_2.size] = scripts\mp\matchdata::gettimefrommatchstart( gettime() );
    var_2[var_2.size] = "type";
    var_2[var_2.size] = var_1;
    var_2[var_2.size] = "name";
    var_2[var_2.size] = var_0;
    self dlog_recordplayerevent( "dlog_event_br_hallucination", var_2 );
}

spawn_enemies_intro( var_0 )
{
    spawn_ending_individual_guys_death( var_0, "announcer" );
}

spawn_exfil_enemies( var_0 )
{
    spawn_ending_individual_guys_death( var_0, "sound" );
}

spawn_entity_carriable( var_0 )
{
    spawn_ending_individual_guys_death( var_0, "music" );
}

spawn_enemy_claymore( var_0 )
{
    spawn_ending_individual_guys_death( var_0.cinematic, "cinematic" );
}

spawn_exfil_heli( var_0 )
{
    spawn_ending_individual_guys_death( var_0, "vfx" );
}

spawn_exfil_chopper( var_0 )
{
    spawn_ending_individual_guys_death( var_0, "scramblehud" );
}

spawn_enemy_drone_turret( var_0 )
{
    spawn_ending_individual_guys_death( var_0.init_standard_range, "fakedamage" );
}

spawn_enemy_juggernaut_single( var_0 )
{
    spawn_ending_individual_guys_death( var_0, "fov" );
}

hasselfrevivetoken()
{
    if ( self.play_alert_music_to_player == 0.0 )
        return ( 1, 1, 1 );

    return level.completesmokinggunquest.play_operator_reply_vo[self.play_animation_old].haspassedsquadleader;
}
