// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

throwing_knife_mp_init()
{
    scripts\cp_mp\utility\script_utility::registersharedfunc( "throwing_knife", "onGive", ::throwing_knife_mp_ongive );
    scripts\cp_mp\utility\script_utility::registersharedfunc( "throwing_knife", "onTake", ::throwing_knife_mp_ontake );
    scripts\cp_mp\utility\script_utility::registersharedfunc( "throwing_knife", "tryToPickup", ::throwing_knife_mp_trytopickup );
}

throwing_knife_mp_ongive( var_0, var_1 )
{
    if ( var_0 == "equip_throwing_knife_fire" )
    {
        self._id_12220 = "iw8_throwingknife_fire_melee_mp";
        thread _id_1221F();
    }
    else if ( var_0 == "equip_throwing_knife_electric" )
    {
        self._id_12220 = "iw8_throwingknife_electric_melee_mp";
        thread _id_1221B();
    }
    else if ( var_0 == "equip_throwing_knife_drill" )
        self._id_12220 = "iw8_throwingknife_drill_melee_mp";
    else
        self._id_12220 = "iw8_knifestab_mp";

    scripts\mp\utility\perk::giveperk( "specialty_equip_throwingKnife" );
}

throwing_knife_mp_ontake( var_0, var_1 )
{
    if ( scripts\mp\utility\perk::_hasperk( "specialty_equip_throwingKnife" ) )
        scripts\mp\utility\perk::removeperk( "specialty_equip_throwingKnife" );

    self._id_12220 = undefined;
}

throwing_knife_mp_trytopickup( var_0 )
{
    if ( scripts\mp\equipment::getequipmentammo( var_0 ) >= scripts\mp\equipment::getequipmentmaxammo( var_0 ) )
        return 0;

    scripts\mp\equipment::incrementequipmentammo( var_0 );

    if ( var_0 == "equip_throwing_knife_fire" )
        scripts\mp\damagefeedback::hudicontype( "throwingknife_fire" );
    else
        scripts\mp\damagefeedback::hudicontype( "throwingknife" );

    return 1;
}

_id_1221F()
{
    self notify( "throwingKnife_clear_fx" );
    self endon( "throwingKnife_clear_fx" );
    self endon( "death_or_disconnect" );
    var_0 = 0;

    for (;;)
    {
        var_1 = 0;
        var_2 = self getheldoffhand();

        if ( !isnullweapon( var_2 ) && var_2.basename == "throwingknife_fire_mp" )
            var_1 = 1;

        if ( var_1 && !var_0 )
            thread _id_1221C();
        else if ( var_0 && !var_1 )
            thread _id_1221E();

        var_0 = var_1;
        waitframe();
    }
}

_id_1221C()
{
    self endon( "death_or_disconnect" );
    self endon( "throwingKnife_end_fx" );
    self.timertexthud = 1;
    self setscriptablepartstate( "equipMtovFXWorld", "neutral", 0 );
    self setscriptablepartstate( "equipMtovFXView", "active", 0 );
    var_0 = 0.4;
    wait( var_0 );
    self setscriptablepartstate( "equipMtovFXWorld", "active", 0 );
    self waittill( "offhand_fired" );
    waitframe();
    thread _id_1221E();
}

_id_1221E()
{
    self notify( "throwingKnife_end_fx" );

    if ( istrue( self.timertexthud ) )
    {
        self setscriptablepartstate( "equipMtovFXWorld", "neutral", 0 );
        self setscriptablepartstate( "equipMtovFXView", "neutral", 0 );
    }

    self.timertexthud = undefined;
}

_id_12217()
{
    self notify( "throwingKnife_clear_fx" );
    thread _id_1221E();
    thread _id_1221A();
}

_id_1221B()
{
    self notify( "throwingKnife_electric_clear_fx" );
    self endon( "throwingKnife_electric_clear_fx" );
    self endon( "death_or_disconnect" );
    var_0 = 0;

    for (;;)
    {
        var_1 = 0;
        var_2 = self getheldoffhand();

        if ( !isnullweapon( var_2 ) && var_2.basename == "throwingknife_electric_mp" )
            var_1 = 1;

        if ( var_1 && !var_0 )
            thread _id_12218();
        else if ( var_0 && !var_1 )
            thread _id_1221A();

        var_0 = var_1;
        waitframe();
    }
}

_id_12218()
{
    self endon( "death_or_disconnect" );
    self endon( "throwingKnife_electric_end_fx" );
    self.timeremaining = 1;
    self setscriptablepartstate( "equipMtovFXWorld", "neutral", 0 );
    self setscriptablepartstate( "equipMtovFXView", "electricKnife", 0 );
    var_0 = 0.4;
    wait( var_0 );
    self setscriptablepartstate( "equipMtovFXWorld", "electricKnife", 0 );
    self waittill( "offhand_fired" );
    waitframe();
    thread _id_1221A();
}

_id_1221A()
{
    self notify( "throwingKnife_electric_end_fx" );

    if ( istrue( self.timeremaining ) )
    {
        self setscriptablepartstate( "equipMtovFXWorld", "neutral", 0 );
        self setscriptablepartstate( "equipMtovFXView", "neutral", 0 );
    }

    self.timeremaining = undefined;
}

_id_12219()
{
    self notify( "throwingKnife_electric_clear_fx" );
    thread _id_1221A();
}
