// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    var_0 = getdvarint( "scr_br_pe_juggernaut_drop_on_death", 0 );
    scripts\mp\gametypes\br_jugg_common.gsc::seq3_has_seen_tiers( "drop_on_death", var_0, "public_event" );
    var_1 = spawnstruct();
    var_1.weight = getdvarfloat( "scr_br_pe_juggernaut_weight", 1.0 );
    var_1.antennae = ::antennae;
    var_1._id_1382D = ::_id_1382D;
    var_1._id_13AB6 = ::_id_13AB6;
    var_1.updatesquadleaderpassstateforteam = getdvarint( "scr_br_pe_juggernaut_max_times", 1 );
    var_1.get_request_backup_alias = scripts\mp\gametypes\br_publicevents.gsc::playerplunderdeposit( "juggernaut", "10 \t5 \t0 \t0 \t\t\t0 \t0 \t0 \t0" );
    scripts\mp\gametypes\br_publicevents.gsc::_id_123D9( 4, var_1 );
    game["dialog"]["public_events_juggernaut_start"] = "public_events_juggernaut_start";
}

_id_1382D()
{
    return level.deadblue.name != "jugg";
}

_id_13AB6()
{
    level endon( "game_ended" );
    level endon( "cancel_public_event" );
    var_0 = enemygunship_updatedebugflashlight();
    wait( var_0 );
}

antennae()
{
    var_0 = scripts\mp\gametypes\br_jugg_common.gsc::playerzombieemp( 1 );
    level.start_whack_a_mole_timer = scripts\engine\utility::array_randomize( level.start_whack_a_mole_timer );
    var_1 = scripts\mp\gametypes\br_jugg_common.gsc::_id_12B6A( var_0, 0 );
    scripts\mp\gametypes\br_public.gsc::brleaderdialog( "public_events_juggernaut_start" );
    level scripts\mp\gametypes\br_jugg_common.gsc::_id_13016( var_1, "public_event" );
    _id_13AA3();
}

_id_13AA3()
{
    for (;;)
    {
        wait 1;
        var_0 = 0;

        foreach ( var_2 in level.endptui )
        {
            if ( var_2.cratetype == "battle_royale_juggernaut" )
            {
                var_0 = 1;
                break;
            }
        }

        if ( !var_0 )
            break;
    }
}

enemygunship_updatedebugflashlight()
{
    var_0 = getdvarfloat( "scr_br_pe_juggernaut_starttime_min", 795.0 );
    var_1 = getdvarfloat( "scr_br_pe_juggernaut_starttime_max", 1110.0 );

    if ( var_1 > var_0 )
        return randomfloatrange( var_0, var_1 );
    else
        return var_0;
}
